// Jsonfy, by André Furquim
//
// This plugin exports your project as JSON
@import "utils.js"
@import "nestor-parser.js"

function generateJson(context){
  var documentPath = getDocumentPath(context)
  var jsonFileName = getJsonFileName(context)
  var destinationPath = getDestination(context)

  var jsonFilePath = generateJsonFile(documentPath, destinationPath, jsonFileName)
  var sketchJson = readSketchGenaratedJson(jsonFilePath)
  // delete file generated by sketchtool.
  // deleteFileFromSystem(jsonFilePath)

  // the ideia is to generate the JSON using sketch dump and format
  // the generated json in a better way so we can build a
  // page using HTML and CSS
  // create an instace od the parser, passing the json generated by Sketch
  var nestorParser = new NestorParser(sketchJson)

  // here we start parsing things..
  nestorParser.generateNestorJson()

  // output the result in a variable
  var output = nestorParser.getNestorJson()
  output = JSON.stringify(output);
  // generate a file with the new json
  log(output)
  var someString = [NSString stringWithFormat:"%@", output],
  filePath = "/Users/"+ NSUserName() +"/Desktop/export.json";
  [someString writeToFile:filePath atomically:true
  encoding:NSUTF8StringEncoding error:nil];
}
